version: '3.8'

services:
  hub-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3307:3306'
    volumes:
      - hub-db-data:/var/lib/mysql

  hub-backend:
    build:
      context: ../hub-community-backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: 0.0.0.0
      PORT: 1340
      PUBLIC_URL: http://localhost:1340
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '1340:1340'
    volumes:
      - ../hub-community-backend:/opt/app
      - /opt/app/node_modules
    depends_on:
      - hub-db

  hub-bff:
    build:
      context: ../hub-community-bff
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 4001
      MANAGER_URL: http://hub-backend:1340
      MANAGER_TOKEN_INTEGRATION: ${MANAGER_TOKEN_INTEGRATION}
    ports:
      - '4001:4001'
    volumes:
      - ../hub-community-bff:/opt/app
      - /opt/app/node_modules
    depends_on:
      - hub-backend

  hub-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: ${NEXT_PUBLIC_GRAPHQL_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: 4010
      HOSTNAME: 0.0.0.0
    ports:
      - '4010:4010'
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    depends_on:
      - hub-bff

volumes:
  hub-db-data:
