FROM node:22-alpine

RUN corepack enable

WORKDIR /opt/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN corepack prepare pnpm@10.13.1 --activate && pnpm install

COPY . .

EXPOSE 4010

CMD ["pnpm", "exec", "next", "dev", "--port", "4010", "--hostname", "0.0.0.0"]
